[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && node node_modules/typescript/bin/tsc"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
